name: CI

on: [pull_request, push]

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.7.2, nightly, 1.6.5]
        julia-arch: [x64]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: runtests
        run: |
             julia --project=. --color=yes -e 'using Pkg; Pkg.test()'
